class FlashcardNotFoundException(Exception):...
class MissingFlashcardAttributeError(Exception):...
class FlashcardCompilationError(Exception):...
class EndofFlashcards(Exception):...

class LaTeXCompilationError(Exception):...
class TypstCompilationError(Exception):...
class NoteExistsError(Exception):...
class CategoryExistsError(Exception):...
class InvalidNameError(Exception):...
class CourseExistsError(Exception):...
class NoItemSelected(Exception):...
class CompilationError(Exception):...

#class LatexmkError(Exception):...
#class LatexmkBadArgsError(Exception):...
#class LatexmkFileNotFoundError(Exception):...
#class LatexmkComponentError(Exception):...
