class FlashcardNotFoundException(Exception):...
class LaTeXCompilationError(Exception):...
class TypstCompilationError(Exception):...
class NoteExistsError(Exception):...
class FolderExistsError(Exception):...
