class FlashcardNotFoundException(Exception):...
class LaTeXCompilationError(Exception):...
class TypstCompilationError(Exception):...
class NoteExistsError(Exception):...
class CategoryExistsError(Exception):...
class InvalidNameError(Exception):...
class CourseExistsError(Exception):...
class NoItemSelected(Exception):...
